language: rust
rust:
  - stable
#  - beta
#  - nightly

before_script:
  - rustup component add clippy

script:
  - cargo clippy --all-targets --all-features -- -D warnings
  - cargo test
  - cargo test --features=unswitched_group
  - cargo run
  - cargo run --features=unswitched_group
