[package]
  name = "veccom"

  # Remember to change version string in README.md.
  version = "0.1.0"
  authors = [
    "Leo Reyzin <leo@algorand.com>",
  ]
  license = "MIT/Apache-2.0"

  description = "Vector commitments with curve BLS12-381"

[dependencies]
  rand = "0.4"
  pairing = { path = "../pairing-fork" }
  sha2 = "0.8"
  libc = { version = "0.2", features = ["align"] }
  ff = { version = "0.4", features = ["derive"] }
  itoa = "0.4"
